name: "PR - api-poi (.NET Core)"

# run on pr to main branch and manually
on:
  pull_request:
    branches:
      - main
    paths:
      - "apis/poi/**"
  workflow_dispatch:

# Set envs
env:
  DOTNET_VERSION: "3.1.x"
  WORKDIR: "apis/poi"

## Set defaults for GitHub Actions runner
defaults:
  run:
    working-directory: "apis/poi"

jobs:
  buildtest:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - run: |
          sudo chown -R root:root $GITHUB_WORKSPACE

      - name: "Check for secrets with Gitleaks"
        id: gitleaks
        uses: DariuszPorowski/github-action-gitleaks@v2
        with:
          source: apis/poi
          config: gitleaksconfig.toml
          report_format: "sarif"
          fail: false
          log_level: debug

      - name: "Output from the gitleaks step"
        run: |
          echo "exitcode: ${{ steps.gitleaks.outputs.exitcode }}"
          echo "result: ${{ steps.gitleaks.outputs.result }}"
          echo "output: ${{ steps.gitleaks.outputs.output }}"
          echo "command: ${{ steps.gitleaks.outputs.command }}"
          echo "report: ${{ steps.gitleaks.outputs.report }}"

      # SARIF upload for repositories with GitHub Advanced Security
      - name: "Upload SARIF report"
        if: steps.gitleaks.outputs.exitcode == 1
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.gitleaks.outputs.report }}

      - name: "Stop workflow if secrets detected"
        if: steps.gitleaks.outputs.exitcode == 1
        run: exit 1

      - run: |
          sudo chown -R runner:runner $GITHUB_WORKSPACE

      - name: "Setup .NET Core ${{ env.DOTNET_VERSION }}"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Restore dependencies"
        run: dotnet restore

      - name: "Build the App"
        run: dotnet build --no-restore

      - name: "Run Unit Tests"
        id: unittest
        run: |
          dotnet test --logger "trx;LogFileName=UnitTestResults.trx" --results-directory ./TestResults --no-build --filter "FullyQualifiedName~UnitTest"

      - name: "Publish test results"
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: Test results
          path: "${{ env.WORKDIR }}/TestResults/UnitTestResults.trx"
          reporter: dotnet-trx
          fail-on-error: false

      - name: "Create an issue (bug)"
        if: failure() && github.event_name != 'pull_request'
        run: |
          body='### Unit Test `failure`
          <details>
          <summary>Workflow details</summary>

          Workflow name: `${{ github.workflow }}`
          Action: `${{ github.event_name }}`
          Job: `${{ github.job }}`
          </details>

          Test details: [Run #${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          Pusher: @${{ github.actor }}'

          title='Unit Tests failure'
          gh issue create --title "${title}" --body "${body}" --label bug --assignee ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Create a PR comment"
        if: failure() && github.event_name == 'pull_request'
        run: |
          body='### Unit Test `failure`
          <details>
          <summary>Workflow details</summary>

          Workflow name: `${{ github.workflow }}`
          Action: `${{ github.event_name }}`
          Job: `${{ github.job }}`
          PR: #${{ github.event.number }}
          </details>

          Test details: [Run #${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          Pusher: @${{ github.actor }}'

          gh pr comment ${{ github.event.number }} --body "${body}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
